FROM golang:1.26-alpine AS builder
RUN apk add --no-cache gcc musl-dev
WORKDIR /app
COPY magna-server/ .
RUN go mod download
RUN CGO_ENABLED=1 go build -o magna-server .

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
RUN mkdir -p /app/data
COPY --from=builder /app/magna-server .
EXPOSE 8080
VOLUME ["/app/data"]
ENV QIMS_DB_PATH=/app/data/daten.db
CMD ["./magna-server"]
