// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function GetActiveFormular() {
  return window['go']['main']['App']['GetActiveFormular']();
}

export function GetDropdowns(arg1) {
  return window['go']['main']['App']['GetDropdowns'](arg1);
}

export function GetDurchfuehrungen(arg1, arg2) {
  return window['go']['main']['App']['GetDurchfuehrungen'](arg1, arg2);
}

export function GetNokIDs() {
  return window['go']['main']['App']['GetNokIDs']();
}

export function GetPruefplan() {
  return window['go']['main']['App']['GetPruefplan']();
}

export function MarkGebracht(arg1, arg2, arg3) {
  return window['go']['main']['App']['MarkGebracht'](arg1, arg2, arg3);
}

export function SaveMessung(arg1) {
  return window['go']['main']['App']['SaveMessung'](arg1);
}

export function SaveMessungDynamic(arg1, arg2) {
  return window['go']['main']['App']['SaveMessungDynamic'](arg1, arg2);
}
