// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckConnection():Promise<string>;

export function GetActiveFormular():Promise<string>;

export function GetDropdowns(arg1:string):Promise<string>;

export function GetDurchfuehrungen(arg1:string,arg2:string):Promise<string>;

export function GetNokIDs():Promise<string>;

export function GetPruefplan():Promise<string>;

export function MarkGebracht(arg1:number,arg2:number,arg3:string):Promise<string>;

export function SaveMessung(arg1:main.Messung):Promise<string>;

export function SaveMessungDynamic(arg1:number,arg2:string):Promise<string>;
