// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateFormular(arg1) {
  return window['go']['main']['App']['ActivateFormular'](arg1);
}

export function AddDropdown(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDropdown'](arg1, arg2, arg3);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function DeleteDropdown(arg1) {
  return window['go']['main']['App']['DeleteDropdown'](arg1);
}

export function DeleteFormular(arg1) {
  return window['go']['main']['App']['DeleteFormular'](arg1);
}

export function DeleteMessung(arg1) {
  return window['go']['main']['App']['DeleteMessung'](arg1);
}

export function DeletePruefplanEntry(arg1) {
  return window['go']['main']['App']['DeletePruefplanEntry'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function ExecuteSQL(arg1) {
  return window['go']['main']['App']['ExecuteSQL'](arg1);
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function GetActiveFormular() {
  return window['go']['main']['App']['GetActiveFormular']();
}

export function GetDBTables() {
  return window['go']['main']['App']['GetDBTables']();
}

export function GetDropdowns(arg1) {
  return window['go']['main']['App']['GetDropdowns'](arg1);
}

export function GetDurchfuehrungen(arg1, arg2) {
  return window['go']['main']['App']['GetDurchfuehrungen'](arg1, arg2);
}

export function GetFormular(arg1) {
  return window['go']['main']['App']['GetFormular'](arg1);
}

export function GetFormulare() {
  return window['go']['main']['App']['GetFormulare']();
}

export function GetMessungen() {
  return window['go']['main']['App']['GetMessungen']();
}

export function GetPruefplan() {
  return window['go']['main']['App']['GetPruefplan']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetWorkflow(arg1) {
  return window['go']['main']['App']['GetWorkflow'](arg1);
}

export function GetWorkflows() {
  return window['go']['main']['App']['GetWorkflows']();
}

export function SaveFormular(arg1) {
  return window['go']['main']['App']['SaveFormular'](arg1);
}

export function SavePruefplanEntry(arg1) {
  return window['go']['main']['App']['SavePruefplanEntry'](arg1);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function SaveWorkflow(arg1) {
  return window['go']['main']['App']['SaveWorkflow'](arg1);
}

export function UpdateFormular(arg1, arg2) {
  return window['go']['main']['App']['UpdateFormular'](arg1, arg2);
}

export function UpdatePruefplanEntry(arg1, arg2) {
  return window['go']['main']['App']['UpdatePruefplanEntry'](arg1, arg2);
}

export function UpdateWorkflow(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkflow'](arg1, arg2);
}
