// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateFormular(arg1:number):Promise<string>;

export function AddDropdown(arg1:string,arg2:string,arg3:number):Promise<string>;

export function CheckConnection():Promise<string>;

export function DeleteDropdown(arg1:number):Promise<string>;

export function DeleteFormular(arg1:number):Promise<string>;

export function DeleteMessung(arg1:number):Promise<string>;

export function DeletePruefplanEntry(arg1:number):Promise<string>;

export function DeleteWorkflow(arg1:number):Promise<string>;

export function ExecuteSQL(arg1:string):Promise<string>;

export function ExportCSV():Promise<string>;

export function GetActiveFormular():Promise<string>;

export function GetDBTables():Promise<string>;

export function GetDropdowns(arg1:string):Promise<string>;

export function GetDurchfuehrungen(arg1:string,arg2:string):Promise<string>;

export function GetFormular(arg1:number):Promise<string>;

export function GetFormulare():Promise<string>;

export function GetMessungen():Promise<string>;

export function GetPruefplan():Promise<string>;

export function GetSetting(arg1:string):Promise<string>;

export function GetWorkflow(arg1:number):Promise<string>;

export function GetWorkflows():Promise<string>;

export function SaveFormular(arg1:string):Promise<string>;

export function SavePruefplanEntry(arg1:string):Promise<string>;

export function SaveSetting(arg1:string,arg2:string):Promise<string>;

export function SaveWorkflow(arg1:string):Promise<string>;

export function UpdateFormular(arg1:number,arg2:string):Promise<string>;

export function UpdatePruefplanEntry(arg1:number,arg2:string):Promise<string>;

export function UpdateWorkflow(arg1:number,arg2:string):Promise<string>;
